### PR TITLE
Support for EN25QH128A and automatic device recognition

### PR DESCRIPTION
**Pull request by fabicodes**
Please read the commit message of the kernel patch. I've didn't test this one yet. The bootloader patch works.

### CODE REVIEW

**Comment by anmaped** [comment]
I think it's fine. Could you test the kernel with the patch ?

**Comment by fabicodes** [comment]
As mentioned on Gitter - kernel works fine with this patch.

TODO:
- [x] Device Recognition
- [x] Partition Offsets
- [x] Persistent Settings
- [ ] Probably more documentation
- [x] GPIO for NV

on the ToDo-List for the Xiaofang S1 - or am I missing something?

**Comment by anmaped** [comment]
After device recognition partition offsets and persistent settings (nvram) came for free. An improvement in documentation is a good idea. What do you mean by `GPIO NV` ?

**Comment by anmaped** [comment]
Let us complete the points in order to close the pull request asap.

**Comment by anmaped** [comment]
@fabi280 Could you test the device recognition based on SPI flash id ? we should add something like `if id=0xXX and SOC=T20L then gpio clear PIN else gpio set PIN`.

**Comment by fabicodes** [comment]
I will continue testing tomorrow night :) I'll also work on the open points
of the pull request.

André Pedro <notifications@github.com> schrieb am So., 24. März 2019, 20:30:

**Comment by anmaped** [comment]
Any news? I want to close it :) I will try to do a modification and then you can test it.

**Comment by fabicodes** [comment]
Device detection on the bootloader-side is working now
`GPIO for NV` means that either GPIO access or the pin for the IR cut is not working

**Comment by anmaped** [comment]
| Camera                  | ID | SOC  | FLASH | GPIO | Notes |
|---------------------|-----|-------|---------|--------|-------|
| Xiaomi Mijia 2018   | SXJ02ZM  | T20L |  X | b_led_pin 76; y_led_pin 75; ir_pin 72; | motor:false; usb:false |
| Xiaomi Xiaofang 1S | | T20L | EN25QH128A | | motor:false |
| Xiaomi Dafang        | | T20X |  X | usb_en_pin 77; b_led_pin 39; y_led_pin 38; ir_pin 49; | |
| Wyze Cam V2         | WYZEC2 | T20X |  X | usb_en_pin 77; b_led_pin 39; y_led_pin 38; ir_pin 49; | motor:false |
| Wyze Cam Pan        | WYZECP1 | T20X |  X | usb_en_pin 77; b_led_pin 39; y_led_pin 38; ir_pin 49; | |

@fabi280 Could you help me to fill this table ? I would like to put a case for each one of these devices in order to recognise them automatically.

edit: https://github.com/anmaped/openfang/blob/master/doc/overview.md

**Comment by anmaped** [comment]
@fabi280 Could you test your SENISC5? DF3 is working.

**Pull request merged**
